.TH AI_READLINE 5 "2024-03-17" "Diomidis Spinellis" \" -*-
 \" nroff -*

.SH NAME
.B ai_cli
\- Configuration file format

.SH SYNOPSIS
The operation of
.BR ai_cli (7)
is controlled by ini-style
configuration files
searched in the order specified in the
.I FILES
section of library's manual page.

.SH DESCRIPTION
Configuration files are searched and loaded in the order specified in
.BR ai_cli (7).
Entries in configuration files read later can override previous ones.

In general, system-wide configuration files are used to specify
default behaviors,
while user configuration files are used for individual tailoring,
such as the specification of the API key or prompts for commands
that are not supported by default.

The following sections describe the supported contents of each
configuration file section.
All section names and options are specified in lowercase.

.SH [PROMPT] SECTION OPTION
.PP
\fIsystem=\fR
.RS 4
The system prompt specifying to context through which the
LLM prompting is made.
A single
.I %s
sequence is replaced when the prompt is sent out as an API request
by the name of the command being executed
(e.g.
.IR mysql ).
.RE

.PP
\fIcontext=\fR
.RS 4
The number of previous commands that will be provided as context.
More context can provide better responses,
but also increases the operation's cost.
.RE

.SH [BINDING] SECTION OPTIONS
.PP
\fIvi=\fR
.RS 4
The single-letter vi movement key on which the AI help is bound.
It can be used when vi key bindings are in effect.
.RE

.PP
\fIemacs=\fR
.RS 4
The Emacs key sequence on which the AI help is bound.
It is specified using
.BR readline (3)
format.
It can be used when Emacs key bindings are in effect.
.RE

.SH [GENERAL] SECTION OPTIONS
.PP
\fIapi=\fR
.RS 4
Specify the API to use: one of anthropic, hal, llamacpp, or openai.
.RE

.PP
\fIlogfile=\fR
.RS 4
Specify a path where requests and responses will be logged.
Useful for debugging and research purposes.
.RE

.PP
\fIresponse_prefix=\fR
.RS 4
When set, the responses will prefixed with the specified string,
e.g. \fItime\fP or \fI#\fP,
followed by a space, before being added to the edit buffer.
.RE

.PP
\fItimestamp=\fR
.RS 4
Setting \fItimestamp\fP to \fItrue\fP will cause the log file
to include the timestamp (in ISO format) of each request or response.
.RE

.SH [ANTHROPIC] SECTION OPTIONS
These options tailor the behavior of queries made to the Anthropic servers.
Refer to the
.UR "https://docs.anthropic.com/claude/reference/messages_post"
Anthropic API documentation
.UE
for more details.

.PP
\fImodel=\fR
.RS 4
The Anthropic model to use, e.g.
.IR claude-3-opus-20240229 .
This affects performance and pricing.
.RE
.PP
\fIendpoint=\fR
.RS 4
The URL of the API endpoint, e.g.  \fChttps://api.anthropic.com/v1/messages\fP.
.RE
.PP
\fImax_tokens=\fR
.PP
\fItemperature=\fR
.PP
\fItop_k=\fR
.PP
\fItop_p=\fR
.PP
\fIversion=\fR
.RS 4
The version to supply to the
.I anthropic-version
HTTP header field.
.RE
.PP

.SH [LLAMACPP] SECTION OPTIONS
These options tailor the behavior of the llama.cpp
queries.
Refer to the 
.UR "https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md"
llama.cpp server documentation
.UE
for more details.

.PP
\fIendpoint=\fR
.RS 4
The URL of the API endpoint, e.g.  \fChttp://localhost:8080/completion\fP.
.RE

.PP
\fItemperature=\fR
.PP
\fItop_k=\fR
.PP
\fItop_p=\fR
.PP
\fIn_predict=\fR
.PP
\fIn_keep=\fR
.PP
\fItfs_z=\fR
.PP
\fItypical_p=\fR
.PP
\fIrepeat_penalty=\fR
.PP
\fIrepeat_last_n=\fR
.PP
\fIpenalize_nl=\fR
.PP
\fIpresence_penalty=\fR
.PP
\fIfrequency_penalty=\fR
.PP
\fImirostat=\fR
.PP
\fImirostat_tau=\fR
.PP
\fImirostat_eta=\fR
.PP
\fIseed=\fR

.SH [OPENAI] SECTION OPTIONS
These options tailor the behavior of the OpenAI
queries.
Refer to the 
.UR "https://platform.openai.com/docs/models"
OpenAI API documentation
.UE
for more details.

.PP
\fIendpoint=\fR
.RS 4
The URL of the API endpoint.
.RE
.PP
\fImodel=\fR
.RS 4
The OpenAI model to use, e.g.
.IR gpt-3.5-turbo .
This affects performance and pricing.
.RE

.PP
\fItemperature=\fR
.RS 4
The sampling temperature to use as a value between 0 and 2.
Higher values, such as 0.8, will make the output more random,
while lower values, such as 0.2, will make it more focused and deterministic.
.RE

.PP
\fIkey=\fR
.RS 4
OpenAI API access key.
Ensure this is specified in a configuration file that is not readable
by entities unauthorized to make OpenAI API requests with the given key.
.RE

.SH [PROMPT-] SECTION OPTIONS
A series of sections starting with
.B prompt-
followed by the name of a program,
such as
.B bash
or
.B mysql
are used to provide program-specific configuration
options for values associated with the
.B prompt
section, and also multishot example prompts
for improving the obtained responses.
The multishot example prompts are provided by
.B ai_cli
at the beginning of each API request.

.PP
\fIcomment=\fR
.RS 4
The line comment sequence for the corresponding tool.
If this is defined, then prompt lines are stored in the
history and provided as context in the form of line comments.
.RE

.PP
\fIuser-n=\fR
.RS 4
A user prompt in natural language.
The \fIn\fP placeholder can take values 1-3.
.RE

.PP
\fIassistant-n=\fR
.RS 4
The ideal response to the user prompt for the program being
specified in the corresponding section.
.RE

.SH EXAMPLE
.RS
.nf
[general]
api = openai

[prompt]
system = You're an assistant providing executable commands for %s.
context = 3

[openai]
endpoint = https://api.openai.com/v1/chat/completions
model = gpt-3.5-turbo
temperature = 1.0
key = sk-hjgds5hljfgs8dfw4ljghljfhfFER344FFFggf84fssddG4k

[llamacpp]
endpoint = http://localhost:8080/completion

[binding]
vi = V
emacs = \\C-xa

[prompt-bash]
context=4
user-1 = List files in current directory
assistant-1 = ls
user-2 = What is the current time and date?
assistant-2 = date
.RE
.fi

.SH FILES
The names and order of configuration files are documented in
.BR ai_cli (7).

.SH SEE ALSO
.BR ai_cli (7).

.SH AUTHOR
Diomidis Spinellis (dds@aueb.gr)

.SH COPYRIGHT
Copyright 2023-2024 Diomidis Spinellis

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
