.TH AI_READLINE 7 "2023-08-10" "Diomidis Spinellis" \" -*-
 \" nroff -*

.SH NAME
.B ai_cli
\- AI enhancement for interactive command-line programs

.SH SYNOPSIS
Set the
.B LD_PRELOAD
(under Linux) or
.B DYLD_INSERT_LIBRARIES
(under macOS)
environment variable to load the library using its full path.
Obtain your Anthropic or OpenAI API key and configure it in the
.B .aicliconfig
file.
Alternatively, setup a running
.UR "https://github.com/ggerganov/llama.cpp"
llama.cpp
.UE
server and configure its endpoint.
Run the interactive command-line programs, such as
.BR bash ,
.BR mysql ,
.BR psql ,
.BR gdb ,
as you normally would.
To obtain AI help,
enter a prompt and press
.B "^X-a"
(Ctrl-X followed by a)
in the (default)
.B Emacs
key binding mode or
.B V
if you have configured
.B vi
key bindings.

.SH DESCRIPTION
The
.B ai_cli
library detects programs that link against
.BR readline (3)
and modifies their interface to allow obtaining help from a
generative pre-trained transformer large language model (LLM).
Specifically,
it creates a
.BR readline (3)
function named
.BR query_ai ,
and binds it to (configurable)
.BR Emacs
and
.BR vi
keys.
When the corresponding key or key sequence is pressed,
suitable prompts are sent to the LLM API endpoint,
and the prompt is replaced with the obtained response.
(The prompt is added in the command-line history for further editing.)
The LLM query contains context from previous commmands
(but not their output),
which allows prompts to refine commands as needed.

The syntax to force preload of the library according to the shell
is as follows.

Bash, Ksh and the traditional Bourne shell (for Linux and macOS):

export LD_PRELOAD=/usr/lib/ai_cli.so

or

export DYLD_INSERT_LIBRARIES=/usr/lib/ai_cli.dylib

C Shell:

setenv LD_PRELOAD=/usr/lib/ai_cli.so

The setting can be made permanent by adding the command
to a shell's configuration file, such as
.BR .bashrc ,
.BR zshrc ", or"
.BR .cshrc .

The operation of
.B ai_cli
can be configured through the files and environment variables listed in the
.I FILES
section and the format documented in
.BR ai_cli (5).

.SH ENVIRONMENT VARIABLES
All configuration entries specified through
.BR ai_cli (5).
can be overridden by supplying to a program's
invocation an environment variable named
\fCAI_CLI_\fIsection\fC_\fIoption\fR,
where dashes are replaced with underscores.
For example, an environment variable setting could be
\fCAI_CLI_prompt_gdb_user_1=Disable breakpoint 3\fP.

.SH FILES
.IR /usr/share/ai-cli/config ,
.IR /usr/local/share/ai-cli/config ,
.IR ai-cli-config ,
.IR $HOME/share/ai-cli/config ,
.IR $HOME/.aicliconfig ,
.I .aicliconfig
\- locations searched for
.B ai_cli
configuration files.

.SH SEE ALSO
.BR ai_cli (5).

.SH BUGS
.B ai_cli
will not work with programs that are linked statically with
.BR readline (3)
rather than using it as a shared library object.

.SH AUTHOR
Diomidis Spinellis (dds@aueb.gr)

.SH COPYRIGHT
Copyright 2023-2024 Diomidis Spinellis

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
